theme: jekyll-theme-minimal
title: Ujwal Gadiraju
description: Assistant Professor, TU Delft
logo: https://media-exp1.licdn.com/dms/image/C4D03AQGYPnQ44w7nQQ/profile-displayphoto-shrink_200_200/0?e=1600905600&v=beta&t=s7sLj2UbjWGQsZjJrtmQ_7dYfAHhCoYyfGUJAe3Lh8U
google_analytics: UA-68030956-2
github:
  is_project_page: false
