theme: jekyll-theme-minimal
title: Ujwal Gadiraju
description: Assistant Professor, TU Delft
logo: https://d1rkab7tlqy5f1.cloudfront.net/_processed_/4/1/csm_Ujwal%20Gadiraju_f3a9377f69.jpg
google_analytics: UA-68030956-1
github:
  is_project_page: false
